---
title: "Zestaw A"
output:
  pdf_document: default
  word_document: default
header-includes: \usepackage[polish]{babel}
---


1. W folderze DebugA znajduje się projekt z kodem w języku C. W pliku main.c w niektórych linijkach są komentarze. Twoim zadaniem jest wpisanie wartości odpowiednich zmiennych po wykonaniu konkretnej linii kodu.

*Punktacja: 1 pkt za każdą poprawną linijkę, łącznie 8 pkt.*

2. Napisz funkcję, która jako argument otrzymuje dodatnią liczbę całkowitą $n$ i zwraca liczbę $\lfloor \sqrt[4]{n} \rfloor$. Nie korzystaj z żadnych gotowych funkcji bibliotecznych. Symbol $\lfloor \ \rfloor$ oznacza część całkowitą danej liczby (największą liczbę całkowitą nieprzekraczającą danej liczby).

|Przykładowe wejście |2| 16 |29|99|
|---|---|---|---|---|
|Przykładowe wyjście | 1 | 2 |2|3|

*Punktacja: 7 pkt.*

3. Napisz funkcję `Zamiana`. Parametrem funkcji ma być wskaźnik do zmiennej typu `double`. Zadaniem funkcji jest zamiana wartości wskazywanej zmiennej z jej odwrotnością (jeśli wartość wynosi np. 5, należy podstawić 1/5 czyli 0.25). Stwórz w programie dwa przypadki testowe.

*Punktacja: 7 pkt.*

4. Napisz funkcję porównującą dwie tablice jednowymiarowe o takich samych rozmiarach. Funkcja powinna zwrócić wartość "1" jeśli tablice są identyczne lub "0" jeśli tablice się różnią.

*Punktacja: 8 pkt.*

5. Napisz funkcję rekurencyjną, która dla otrzymanej w argumentach
pary nieujemnych liczb całkowitych $n$ i $m$ zwraca wartość $f(n,m)$
gdzie funkcja $f$ jest zdefiniowana w następujący sposób:

$$f(n,0)=2,$$
$$f(0,m)=m,$$
$$f(n,m)=f(n-1,m)\cdot f(n,m-1)+7$$

Przypadki testowe dla funkcji:

| $n$ | $m$ | $f(n,m)$ |
|---|---|---|
| 0 | 4 | 4 |
| 2 | 0 | 2 |
| 3 | 2 | 36031 |

*Punktacja: 7 pkt.*

6. Stwórz program, w którym wykonasz poniższe czynności:
* stwórz tablicę jednowymiarową 7-elementową typu `int` i uzupełnij ją dowolnym wartościami,
* za pomocą pętli sprawdź ile liczb w tej tablicy jest podzielnych przez 7, wynik wyświetl na konsoli (uwaga: uwzględnij liczby dodatnie, ujemne i zero, zero dzieli się przez każdą liczbę).

*Punktacja: 7 pkt.*


7. W folderze PoprawA znajduje się kod w języku C, który nie spełnia zasad kompilacji. Popraw kod modyfikując co najwyżej 2 linijki tak, aby się kompilował. Zabronioną operacją jest komentowanie kodu.


*Punktacja: 6 pkt.*

**Po zakończonej pracy wszystkie pliki z kodem (własne i poprawione) umieść w jednym folderze na puplicie komputera. Spakuj folder i zmień nazwę archiwum pokrywającą się z Twoim numerem indeksu/albumu/legitymacji. Sprawdzeniu podlegać będzie tylko i wyłączenie zawartość archiwum.**

